language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
  - nightly

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - make test

after_success:
  coveralls
